enable_testing()
function(auto_tester NAME SOLUTION TEST)
    # include(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/Catch.cmake)
    include(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/CompilerWarnings.cmake)
    set(SOLUTION_DIR ${CMAKE_CURRENT_SOURCE_DIR} CACHE PATH "Path to solution")
    set(CMAKE_CXX_STANDARD 17)
    set(CMAKE_CXX_EXTENSIONS OFF)
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../external/doctest catch2)
    add_executable(${NAME}_test ${SOLUTION_DIR}/${SOLUTION} ${TEST})
    target_include_directories(${NAME}_test PUBLIC ${SOLUTION_DIR} ${CMAKE_CURRENT_SOURCE_DIR})
    target_link_libraries(${NAME}_test PUBLIC Catch2::Catch2)
    set_project_warnings(${NAME}_test)
    add_test(${NAME}_test ${NAME}_test)
    # catch_discover_tests(${NAME}_test TEST_PREFIX ${NAME}::)
endfunction()
